# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9764df9e033ebd43e2f375378109e5dcac15636b3d2367f320c6901936c1e2c4588a8981cd9c63ac80416f7e60bfbb52296510424492bf83d5006838544944d0

test:
  secret_key_base: 32fab53fc0b2aac3e76d1e18475175a4828de5437999dab9e905d7ca25d38b788515e072469d6879d5cd56a43138108201546c1f49415f34a2515798c5dbd744

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
